-- Migration V2: core business schema.
--
-- Conventions (see V1): TEXT UUID primary keys, ISO-8601 UTC timestamps,
-- nullable `deleted_at` soft delete. Ids and timestamps are generated by the
-- Rust backend, so columns are declared NOT NULL without DB defaults.
--
-- Intentional deviations from the global convention:
--   * `task_tags` is a pure join table: composite key, no UUID/audit columns.
--   * `settings` is key/value: TEXT key primary, no UUID/created_at.

-- Projects -----------------------------------------------------------------
CREATE TABLE projects (
    id          TEXT PRIMARY KEY,
    name        TEXT NOT NULL,
    description TEXT,
    color       TEXT,
    icon        TEXT,
    due_at      TEXT,
    status      TEXT NOT NULL DEFAULT 'active'
                CHECK (status IN ('active', 'archived')),
    sort_order  TEXT NOT NULL,
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL,
    deleted_at  TEXT
);

-- Board columns ------------------------------------------------------------
CREATE TABLE board_columns (
    id         TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name       TEXT NOT NULL,
    position   TEXT NOT NULL,
    is_done    INTEGER NOT NULL DEFAULT 0 CHECK (is_done IN (0, 1)),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT
);

CREATE INDEX idx_board_columns_project ON board_columns(project_id, position);

-- Tasks --------------------------------------------------------------------
CREATE TABLE tasks (
    id           TEXT PRIMARY KEY,
    project_id   TEXT REFERENCES projects(id) ON DELETE SET NULL,
    title        TEXT NOT NULL,
    note         TEXT,
    priority     TEXT NOT NULL DEFAULT 'none'
                 CHECK (priority IN ('high', 'medium', 'low', 'none')),
    column_id    TEXT REFERENCES board_columns(id) ON DELETE SET NULL,
    due_at       TEXT,
    completed_at TEXT,
    repeat_rule  TEXT,
    sort_order   TEXT NOT NULL,
    created_at   TEXT NOT NULL,
    updated_at   TEXT NOT NULL,
    deleted_at   TEXT
);

CREATE INDEX idx_tasks_project ON tasks(project_id);
CREATE INDEX idx_tasks_column ON tasks(column_id);
CREATE INDEX idx_tasks_due_at ON tasks(due_at);
CREATE INDEX idx_tasks_completed_at ON tasks(completed_at);

-- Subtasks -----------------------------------------------------------------
CREATE TABLE subtasks (
    id         TEXT PRIMARY KEY,
    task_id    TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    title      TEXT NOT NULL,
    done       INTEGER NOT NULL DEFAULT 0 CHECK (done IN (0, 1)),
    sort_order TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT
);

CREATE INDEX idx_subtasks_task ON subtasks(task_id);

-- Tags (global, shared across projects) ------------------------------------
CREATE TABLE tags (
    id         TEXT PRIMARY KEY,
    name       TEXT NOT NULL COLLATE NOCASE UNIQUE,
    color      TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT
);

CREATE TABLE task_tags (
    task_id TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    tag_id  TEXT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (task_id, tag_id)
) WITHOUT ROWID;

CREATE INDEX idx_task_tags_tag ON task_tags(tag_id);

-- Comments ------------------------------------------------------------------
CREATE TABLE comments (
    id         TEXT PRIMARY KEY,
    task_id    TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    body       TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT
);

CREATE INDEX idx_comments_task ON comments(task_id);

-- Time entries --------------------------------------------------------------
CREATE TABLE time_entries (
    id         TEXT PRIMARY KEY,
    task_id    TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    started_at TEXT,
    ended_at   TEXT,
    duration   INTEGER NOT NULL DEFAULT 0 CHECK (duration >= 0),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT
);

CREATE INDEX idx_time_entries_task ON time_entries(task_id);
CREATE INDEX idx_time_entries_started_at ON time_entries(started_at);

-- Settings (key/value) ------------------------------------------------------
CREATE TABLE settings (
    key        TEXT PRIMARY KEY,
    value      TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

-- Full-text search (FTS5 external-content tables + sync triggers) -----------
-- `trigram` tokenizer matches CJK/Latin substrings of >= 3 characters;
-- queries below 3 characters fall back to LIKE (M3). Soft-deleted rows stay
-- in the index, so queries must join and filter on `deleted_at IS NULL`.
CREATE VIRTUAL TABLE task_search USING fts5(
    title,
    note,
    content='tasks',
    content_rowid='rowid',
    tokenize='trigram'
);

CREATE VIRTUAL TABLE comment_search USING fts5(
    body,
    content='comments',
    content_rowid='rowid',
    tokenize='trigram'
);

CREATE TRIGGER tasks_ai AFTER INSERT ON tasks BEGIN
    INSERT INTO task_search(rowid, title, note)
    VALUES (new.rowid, new.title, new.note);
END;

CREATE TRIGGER tasks_ad AFTER DELETE ON tasks BEGIN
    INSERT INTO task_search(task_search, rowid, title, note)
    VALUES ('delete', old.rowid, old.title, old.note);
END;

CREATE TRIGGER tasks_au AFTER UPDATE OF title, note ON tasks BEGIN
    INSERT INTO task_search(task_search, rowid, title, note)
    VALUES ('delete', old.rowid, old.title, old.note);
    INSERT INTO task_search(rowid, title, note)
    VALUES (new.rowid, new.title, new.note);
END;

CREATE TRIGGER comments_ai AFTER INSERT ON comments BEGIN
    INSERT INTO comment_search(rowid, body) VALUES (new.rowid, new.body);
END;

CREATE TRIGGER comments_ad AFTER DELETE ON comments BEGIN
    INSERT INTO comment_search(comment_search, rowid, body)
    VALUES ('delete', old.rowid, old.body);
END;

CREATE TRIGGER comments_au AFTER UPDATE OF body ON comments BEGIN
    INSERT INTO comment_search(comment_search, rowid, body)
    VALUES ('delete', old.rowid, old.body);
    INSERT INTO comment_search(rowid, body) VALUES (new.rowid, new.body);
END;
